spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  thymeleaf:
    cache: false
    enabled: false
  main:
    allow-bean-definition-overriding: true
